# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:physics.* OR cat:math.* OR cat:stat.*'

# 検索キーワード
keywords:
        quantum annealing: 1
        simulated annealing: 1
        combinatorial optimization: 1
        quantum: 1

# 通知の閾値
score_threshold: 0

config: '<@UHMA7FPDM>'
