name: Carrier Owl

on:
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    - cron:  '50 0 * * 0,3,4,5,6'
  workflow_dispatch:

  push:
    branches:
      - test-send-to-slack

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Run owl
        run:
          python src/carrier_owl.py
        env:
          SLACK_ID: ${{ secrets.SLACK_ID }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
